services:
  db:
    container_name: db_postgres
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:${PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    container_name: app_django
    build: ./app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py init-db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - PORT=${PORT}
      - HOST=db
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local