databases:
  - name: django-db
    plan: free
    databaseName: ecocycle
    user: admingrupo1

services:
  - type: web
    plan: free
    name: django-app
    runtime: python
    buildCommand: "app/build.sh"
    startCommand: "cd app && python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4