# Generated by Django 5.1.1 on 2024-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recolector',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
