# Generated by Django 5.1.1 on 2024-10-10 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_global', models.IntegerField(unique=True)),
                ('id_local', models.IntegerField(unique=True)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecocycle.material')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
