# Generated by Django 5.1 on 2024-09-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0002_administrador_username_recolector_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CentroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocycle.centro')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocycle.material')),
            ],
            options={
                'db_table': 'centro_material',
                'unique_together': {('material', 'centro')},
            },
        ),
        migrations.AddField(
            model_name='centro',
            name='materiales',
            field=models.ManyToManyField(through='ecocycle.CentroMaterial', to='ecocycle.material'),
        ),
    ]
