# Generated by Django 5.1 on 2024-10-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='materiales',
            field=models.ManyToManyField(blank=True, related_name='puntos', to='ecocycle.material'),
        ),
    ]
