# Generated by Django 5.1.1 on 2024-10-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0003_alter_pedido_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_global',
            new_name='id_centro',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_local',
            new_name='id_deposito',
        ),
    ]
