# Generated by Django 5.1 on 2024-09-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0003_recoleccion_aprobada_centromaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='notificacion',
            field=models.BooleanField(default=False),
        ),
    ]
