# Generated by Django 5.1.1 on 2024-10-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0004_rename_fecha_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='unique_deposito_material_fecha',
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('deposito', 'material', 'fecha_creacion'), name='unique_deposito_material_fecha-creacion'),
        ),
    ]
