# Generated by Django 5.1.1 on 2024-10-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0004_rename_id_global_pedido_id_centro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecocycle.centro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecocycle.deposito'),
        ),
    ]
