# Generated by Django 5.1 on 2024-10-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0004_recoleccion_notificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoleccion',
            old_name='aprobada',
            new_name='finalizada',
        ),
    ]
