# Generated by Django 5.1.1 on 2024-10-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0005_alter_pedido_id_centro_alter_pedido_id_deposito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_centro',
            new_name='centro',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_deposito',
            new_name='deposito',
        ),
    ]
