# Generated by Django 5.1 on 2024-10-02 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0005_rename_aprobada_recoleccion_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoleccion',
            name='semana',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
