# Generated by Django 5.1 on 2024-10-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0006_alter_recoleccion_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoleccion',
            name='observaciones',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
