# Generated by Django 5.1.1 on 2024-10-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocycle', '0006_rename_id_centro_pedido_centro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecocycle.centro'),
        ),
    ]
