from models.usuario import Usuario
from models.administrador import Administrador
from models.recolector import Recolector
from models.centro import Centro
from models.lugar import Lugar
from models.punto import Punto
from models.deposito import Deposito
from models.material import Material
from models.recoleccion import Recoleccion
from app.ecocycle.models.recoleccion_material import RecoleccionMaterial